"""A-domain property-based invariants (INDEX_M22_PROPTEST, A-side).

The existing adapter suite is discriminative-first (this one input -> this one
behaviour). This file adds the complementary layer: laws that must hold for ANY
legal input, generated by hypothesis. Scope is the A domain only (adapters):

  * P10  ``target_coord`` -- level+coord -> mixable target coordinate lands inside
         the ``[P_TARGET_LO, P_TARGET_HI]`` window and is monotone in ``coord``;
         a dropped level is a LOUD rejection (never a silent fallback).
  * CAS  content_store put/get round-trip is byte-exact, its oid == sha256, and
         identical content collapses to one object (dedup by content addressing).
  * PROV DomainProvider cross-hook consistency (the invariant check_complete
         guards) holds for both real providers, and truth-face mu are finite.

Determinism reconciliation (INDEX_M22 §7, applied INLINE because conftest.py is
out of scope for this batch): every generative property runs under ``_PROP`` --
``derandomize=True`` (same source+input -> bit-for-bit reproducible across runs)
and ``database=None`` (no dependency on the machine-local ``.hypothesis`` cache).
Any counterexample is to be pinned as an ``@example`` in git, never left to the
failure database. The window endpoints are pinned as ``@example`` up front.
"""

from __future__ import annotations

import hashlib
import math
import tempfile
from pathlib import Path

import pytest
from hypothesis import example, given, settings, strategies as st

from expos.adapters import content_store as store_ca
from expos.adapters.base import AdapterError
from expos.adapters.providers.catalyst_screen import CatalystScreenProvider
from expos.adapters.providers.solvent_screen import SolventScreenProvider
from expos.adapters.wet.screen import P_TARGET_HI, P_TARGET_LO, target_coord

#: Shared determinism profile for every generative property in this file (§7).
_PROP = settings(
    derandomize=True,      # fixed seed derived from the test -> reproducible
    database=None,         # do not depend on the local .hypothesis cache
    deadline=None,         # generative work may be slow on a shared box
    max_examples=200,
    print_blob=False,      # never emit @reproduce_failure blobs
)

_PROVIDERS = [SolventScreenProvider, CatalystScreenProvider]


# ======================================================================
# P10 — target_coord: window containment + monotonicity + loud on miss
# ======================================================================

@_PROP
@example(coord=0.0)   # window low edge: target_coord == P_TARGET_LO
@example(coord=1.0)   # window high edge: target_coord == P_TARGET_HI
@given(coord=st.floats(min_value=0.0, max_value=1.0))
def test_target_coord_lands_in_window(coord):
    """For any legal descriptor (coord in [0,1]), target_coord(level) lies inside
    the mixable [P_TARGET_LO, P_TARGET_HI] window -- never outside, so a mapped
    coordinate is always pipette-feasible."""
    v = target_coord("L", {"L": {"coord": coord}})
    assert P_TARGET_LO <= v <= P_TARGET_HI


@_PROP
@given(
    a=st.floats(min_value=0.0, max_value=1.0),
    b=st.floats(min_value=0.0, max_value=1.0),
)
def test_target_coord_is_monotone_in_coord(a, b):
    """target_coord is monotone non-decreasing in the normalized coordinate
    (it is the affine lo + coord*(hi-lo), hi>lo)."""
    va = target_coord("L", {"L": {"coord": a}})
    vb = target_coord("L", {"L": {"coord": b}})
    if a <= b:
        assert va <= vb
    else:
        assert va >= vb


@_PROP
@given(
    levels=st.lists(st.text(min_size=1), min_size=2, max_size=6, unique=True),
    coord=st.floats(min_value=0.0, max_value=1.0),
)
def test_target_coord_dropped_level_is_loud(levels, coord):
    """A sub-mapping that OMITS the queried level is rejected loudly (AdapterError)
    -- a candidate whose level the map cannot place must never slip through as a
    default. Property-ized 'delete one level -> loud reject'."""
    victim = levels[0]
    sub = {lv: {"coord": coord} for lv in levels[1:]}
    assert victim not in sub
    with pytest.raises(AdapterError):
        target_coord(victim, sub)


# ======================================================================
# CAS — content_store round-trip / content-address / dedup
# ======================================================================

@_PROP
@example(data=b"")        # empty payload boundary
@given(data=st.binary(min_size=0, max_size=2048))
def test_content_store_roundtrip_and_content_address(data):
    """For any bytes: put->get is byte-exact, the oid equals sha256(bytes), and a
    second put of identical content returns the SAME oid (dedup is the by-product
    of content addressing). Isolated per example via a private temp dir."""
    with tempfile.TemporaryDirectory() as d:
        root = Path(d) / "cas"
        src = Path(d) / "blob.bin"
        src.write_bytes(data)

        oid = store_ca.put(src, root=root)
        assert oid == hashlib.sha256(data).hexdigest()        # oid == sha256
        assert store_ca.get(oid, root=root).read_bytes() == data  # byte-exact roundtrip

        src2 = Path(d) / "blob2.bin"
        src2.write_bytes(data)
        assert store_ca.put(src2, root=root) == oid           # same content -> one oid


# ======================================================================
# PROV — DomainProvider cross-hook consistency (property-ized)
# ======================================================================

@pytest.mark.parametrize("prov_cls", _PROVIDERS)
def test_provider_wet_dry_level_set_identity(prov_cls):
    """Invariant (the one check_complete guards, here property-ized directly): a
    provider's wet_coords level set == its compute_targets key set -- every level the
    dry leg can compute is one the wet leg can prepare, and vice versa. Also: every
    wet coordinate is a legal target_coord input landing in-window."""
    p = prov_cls()
    assert set(p.wet_coords()) == set(p.compute_targets())
    for level, coords in p.wet_coords().items():
        for coord_name in coords:
            v = target_coord(level, dict(p.wet_coords()), coord_name)
            assert P_TARGET_LO <= v <= P_TARGET_HI


@pytest.mark.parametrize("prov_cls", _PROVIDERS)
def test_provider_truth_profiles_are_finite_floats(prov_cls):
    """truth_profiles() mu are finite floats (a well-formed hidden-face peak), and
    the face set is non-empty -- the value-range half of the check_complete gate."""
    p = prov_cls()
    faces = p.truth_profiles()
    assert faces  # non-empty
    for face, mu in faces.items():
        assert isinstance(mu, float) and math.isfinite(mu)
